
name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasi

      - name: Test
        run: |
          cargo test

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - run: npm run build

      - name: e2e
        working-directory: e2e
        run: |
          npm ci
          npm test
